# Generated by Django 6.0.2 on 2026-02-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
