# Generated by Django 6.0.2 on 2026-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drink_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
